---
- name: Prepare EC2 for Reelfiyat Docker Deployment
  hosts: web_servers
  become: true
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemctl:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes